import { useState } from 'react';import type { EmailTemplate } from '@contracts/types';import { TextInput, Textarea, Select } from '@/components/ui/FormField';import { WarmButton } from '@/components/ui/WarmButton';
/**
 * 信件類型。留空時 `emailCompose.letterKindOf` 會退回用名稱猜，而名稱猜得出來的東西有限——
 * 猜錯的代價是一封只想商量改期的信被掛上「我確認出席」的按鈕。所以這裡讓人直接選。
 */
const LETTER_KINDS:{value:string;label:string}[]=[
  {value:'',label:'（留空＝依名稱猜）'},
  {value:'confirm',label:'confirm｜確認信（載入時會勾上出席確認按鈕）'},
  {value:'follow_up',label:'follow_up｜催覆信（帶回覆期限，會勾上出席確認按鈕）'},
  {value:'notice',label:'notice｜通知信（不附出席確認按鈕）'},
  {value:'bulk',label:'bulk｜群發宣傳信'},
  {value:'instructor',label:'instructor｜講師／客座信'},
  {value:'reject',label:'reject｜婉拒信'},
];
/** 依服務線分好的一組範本。結構刻意不從 admin 匯入型別：這個元件不需要知道後台的模組佈局。 */
export interface EmailTemplateGroup{label:string;items:EmailTemplate[];}
export interface EmailTemplateManagerProps{templates:EmailTemplate[];/** 有傳就以分組顯示清單（標題列＋各線範本）；沒傳維持原本的一長串平名單。 */groups?:EmailTemplateGroup[];previewValues?:Record<string,string>;onSave:(template:EmailTemplate)=>void;onDelete:(template:EmailTemplate)=>void;}
/** Controlled CRUD UI for email templates; does not send mail. */ export function EmailTemplateManager({templates,groups,previewValues={姓名:'王小安',場次:'7 月示範場',Meet連結:'https://meet.google.com/demo',時段:'週日晚上'},onSave,onDelete}:EmailTemplateManagerProps){const [editing,setEditing]=useState<EmailTemplate|undefined>(templates[0]);const [confirming,setConfirming]=useState<string|undefined>();const template=editing;if(!template)return <WarmButton onClick={()=>setEditing({id:`draft-${crypto.randomUUID()}`,name:'新範本',subject:'',body:'',createdAt:new Date().toISOString()})}>新增範本</WarmButton>;const render=(text:string)=>Object.entries(previewValues).reduce((out,[key,value])=>out.replaceAll(`{{${key}}}`,value),text);return <div className="email-template-manager"><aside className="email-template-list">{(groups??[{label:'',items:templates}]).map(group=><section key={group.label||'__all__'} className="email-template-group">{group.label?<h4 className="email-template-group__label ops-nav-label">{group.label}</h4>:null}{group.items.length?group.items.map(item=><button type="button" key={item.id} onClick={()=>setEditing(item)}>{item.name}</button>):<p className="email-template-group__empty">這條服務線還沒有專屬範本。</p>}</section>)}<WarmButton size="sm" onClick={()=>setEditing({id:`draft-${crypto.randomUUID()}`,name:'新範本',subject:'',body:'',createdAt:new Date().toISOString()})}>新增</WarmButton></aside><main><TextInput label="範本名稱" name="name" value={template.name} onChange={event=>setEditing({...template,name:event.target.value})}/><TextInput label="主旨" name="subject" value={template.subject} onChange={event=>setEditing({...template,subject:event.target.value})}/><Select label="信件類型" name="letter_kind" helpText="留空＝依名稱猜，可能猜錯（例：「改期確認信」含「確認信」）。" options={LETTER_KINDS} value={template.letterKind??''} onChange={event=>setEditing({...template,letterKind:(event.target.value||undefined) as EmailTemplate['letterKind']})}/><Textarea label="內容" name="body" value={template.body} onChange={event=>setEditing({...template,body:event.target.value})}/><div>{['姓名','場次','Meet連結','時段'].map(key=><button type="button" key={key} onClick={()=>setEditing({...template,body:`${template.body}{{${key}}}`})}>{`{{${key}}}`}</button>)}</div><h3>即時預覽</h3><strong>{render(template.subject)}</strong><p>{render(template.body)}</p><WarmButton onClick={()=>onSave(template)}>儲存</WarmButton>{/* 刪除確認做在畫面裡，不用 window.confirm：原生對話框在自動化瀏覽器裡會被自動取消，代驗做不到。 */}{confirming===template.id?<><WarmButton variant="danger" onClick={()=>{setConfirming(undefined);onDelete(template);}}>確定刪除「{template.name}」</WarmButton><WarmButton variant="secondary" onClick={()=>setConfirming(undefined)}>取消</WarmButton></>:<WarmButton variant="danger" onClick={()=>setConfirming(template.id)}>刪除…</WarmButton>}</main></div>}
