import { useEffect, useMemo, useState } from 'react';
import { adminListProjects } from '@/lib/api';
import type { Project } from '@contracts/types';
import { TextInput, Textarea, Select } from '@/components/ui/FormField/FormField';
import { WarmButton } from '@/components/ui/WarmButton/WarmButton';
import { archiveOperationalCase, archiveServiceRecord, listOperationalCases, saveOperationalCase, saveServiceRecord, transferCase, type OperationalCase } from '../operations/case-api';
import { listNotes, listTeamMembers, saveNote, saveTask } from '../operations/api';
import type { InternalNote, TeamMemberRecord } from '../operations/types';
import { EmptyPanel, InlineSpinner, OpsNotice, PageHeader, StatusPill } from '../operations/components';

export default function CasesOperationsPage() {
  const [items, setItems] = useState<OperationalCase[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [team, setTeam] = useState<TeamMemberRecord[]>([]); const [selectedId, setSelectedId] = useState<string>(); const [notes, setNotes] = useState<InternalNote[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState<string>(); const [error, setError] = useState<string>();
  const selected = items.find((item) => item.id === selectedId);
  const [caseDraft, setCaseDraft] = useState<Partial<OperationalCase>>({}); const [record, setRecord] = useState<{ kind: 'service' | 'contact' | 'note'; title: string; content: string; occurredAt: string }>({ kind: 'service', title: '', content: '', occurredAt: new Date().toISOString().slice(0, 16) }); const [note, setNote] = useState(''); const [transfer, setTransfer] = useState({ to: '', reason: '' });
  const reload = async () => { const [cases, ps, members] = await Promise.all([listOperationalCases(), adminListProjects(), listTeamMembers()]); setItems(cases); setProjects(ps); setTeam(members.filter((m) => ['owner', 'admin_collab'].includes(m.role))); if (!selectedId && cases[0]) setSelectedId(cases[0].id); };
  useEffect(() => { reload().catch((e: unknown) => setError(e instanceof Error ? e.message : '讀取個案失敗')).finally(() => setLoading(false)); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (selected) { setCaseDraft({ ...selected }); listNotes({ caseId: selected.id }).then(setNotes).catch(() => setNotes([])); } }, [selectedId, items]); // eslint-disable-line react-hooks/exhaustive-deps
  const filtered = useMemo(() => items.filter((item) => `${item.displayName} ${item.summary ?? ''}`.toLowerCase().includes(search.toLowerCase())), [items, search]);
  const saveCase = async () => { if (!caseDraft.projectId || !caseDraft.displayName) { setError('請填寫計畫與個案名稱。'); return; } try { await saveOperationalCase({ ...caseDraft, projectId: caseDraft.projectId, displayName: caseDraft.displayName, serviceType: caseDraft.serviceType ?? 'ongoing', status: caseDraft.status ?? 'active' }); await reload(); setNotice('個案資料已儲存。'); } catch (e) { setError(e instanceof Error ? e.message : '儲存個案失敗'); } };
  const addRecord = async () => { if (!selected || !record.title.trim()) return; try { await saveServiceRecord({ caseId: selected.id, ...record, occurredAt: new Date(record.occurredAt).toISOString() }); setRecord({ kind: 'service', title: '', content: '', occurredAt: new Date().toISOString().slice(0, 16) }); await reload(); setNotice('服務紀錄已新增。'); } catch (e) { setError(e instanceof Error ? e.message : '新增紀錄失敗'); } };
  const addNote = async () => { if (!selected || !note.trim()) return; await saveNote({ caseId: selected.id, noteType: 'general', content: note }); setNote(''); setNotes(await listNotes({ caseId: selected.id })); };
  const addTask = async () => { if (!selected) return; await saveTask({ projectId: selected.projectId, caseId: selected.id, contactId: selected.contactId, title: `追蹤：${selected.displayName}`, priority: 'normal', status: 'open' }); setNotice('已建立追蹤待辦。'); };
  const doTransfer = async () => { if (!selected || !transfer.to || !transfer.reason.trim()) { setError('請選擇接手者並填寫轉移原因。'); return; } await transferCase(selected.id, selected.assignedTo, transfer.to, transfer.reason); setTransfer({ to: '', reason: '' }); await reload(); setNotice('個案已轉移並留下紀錄。'); };
  const createNew = () => { setSelectedId(undefined); setCaseDraft({ projectId: projects[0]?.id, displayName: '', serviceType: 'ongoing', status: 'active' }); };
  return <section className="ops-section"><PageHeader eyebrow="持續服務" title="個案管理" description="建立、編輯、轉移、結案與保存具版本歷程的服務紀錄。" actions={<WarmButton onClick={createNew}>＋ 建立個案</WarmButton>} />{notice ? <OpsNotice tone="success">{notice}</OpsNotice> : null}{error ? <OpsNotice tone="danger">{error}</OpsNotice> : null}{loading ? <InlineSpinner /> : <div className="ops-split">
    <aside className="ops-panel ops-panel--flush"><div className="ops-search"><TextInput label="搜尋個案" value={search} onChange={(e) => setSearch(e.target.value)} /></div>{filtered.length ? <div className="ops-list">{filtered.map((item) => <button type="button" key={item.id} className={`ops-list-button ${item.id === selectedId ? 'ops-list-button--active' : ''}`} onClick={() => setSelectedId(item.id)}><div><strong>{item.displayName}</strong><p>{item.summary || '尚無摘要'}</p></div><StatusPill tone={item.status === 'active' ? 'green' : item.status === 'closed' ? 'gray' : 'yellow'}>{item.status}</StatusPill></button>)}</div> : <EmptyPanel title="沒有個案" />}</aside>
    <main className="ops-section"><article className="ops-panel"><div className="ops-panel-header"><h2>{caseDraft.id ? caseDraft.displayName : '建立新個案'}</h2>{caseDraft.id ? <StatusPill tone={caseDraft.status === 'active' ? 'green' : 'gray'}>{caseDraft.status}</StatusPill> : null}</div><div className="ops-form-grid"><Select label="所屬計畫" value={caseDraft.projectId ?? ''} onChange={(e) => setCaseDraft({ ...caseDraft, projectId: e.target.value })}>{projects.map((p) => <option value={p.id} key={p.id}>{p.name}</option>)}</Select><TextInput label="個案顯示名稱" value={caseDraft.displayName ?? ''} onChange={(e) => setCaseDraft({ ...caseDraft, displayName: e.target.value })} /><Select label="服務型態" value={caseDraft.serviceType ?? 'ongoing'} onChange={(e) => setCaseDraft({ ...caseDraft, serviceType: e.target.value as OperationalCase['serviceType'] })}><option value="ongoing">持續服務</option><option value="single">單次服務</option></Select><Select label="狀態" value={caseDraft.status ?? 'active'} onChange={(e) => setCaseDraft({ ...caseDraft, status: e.target.value as OperationalCase['status'] })}><option value="active">進行中</option><option value="paused">暫停</option><option value="closed">結案</option></Select><div className="ops-full"><Textarea label="個案摘要" rows={4} value={caseDraft.summary ?? ''} onChange={(e) => setCaseDraft({ ...caseDraft, summary: e.target.value })} /></div>{caseDraft.status === 'closed' ? <div className="ops-full"><Textarea label="結案原因" value={caseDraft.closeReason ?? ''} onChange={(e) => setCaseDraft({ ...caseDraft, closeReason: e.target.value })} /></div> : null}</div><div className="ops-button-row"><WarmButton onClick={() => void saveCase()}>儲存個案</WarmButton>{selected ? <><WarmButton variant="secondary" onClick={() => void addTask()}>建立追蹤</WarmButton><WarmButton variant="secondary" onClick={() => { if (confirm('確定封存此個案？')) void archiveOperationalCase(selected.id).then(reload); }}>封存</WarmButton></> : null}</div></article>
    {selected ? <><article className="ops-panel"><div className="ops-panel-header"><h2>轉移負責人</h2></div><div className="ops-form-grid"><Select label="接手者" value={transfer.to} onChange={(e) => setTransfer({ ...transfer, to: e.target.value })}><option value="">請選擇</option>{team.map((m) => <option key={m.id} value={m.userId}>{m.displayName || m.email}</option>)}</Select><TextInput label="轉移原因" value={transfer.reason} onChange={(e) => setTransfer({ ...transfer, reason: e.target.value })} /></div><WarmButton onClick={() => void doTransfer()}>確認轉移</WarmButton></article><article className="ops-panel"><div className="ops-panel-header"><h2>內部註記</h2></div><Textarea label="新增註記" value={note} onChange={(e) => setNote(e.target.value)} /><div className="ops-button-row"><WarmButton onClick={() => void addNote()}>儲存註記</WarmButton></div>{notes.map((n) => <div className="ops-note" key={n.id}><p>{n.content}</p><small>第 {n.revision} 版 · {new Date(n.createdAt).toLocaleString('zh-TW')}</small></div>)}</article><article className="ops-panel"><div className="ops-panel-header"><h2>服務與聯絡紀錄</h2></div><div className="ops-form-grid"><Select label="紀錄類型" value={record.kind} onChange={(e) => setRecord({ ...record, kind: e.target.value as 'service' | 'contact' | 'note' })}><option value="service">服務</option><option value="contact">聯絡</option><option value="note">紀錄</option></Select><TextInput type="datetime-local" label="發生時間" value={record.occurredAt} onChange={(e) => setRecord({ ...record, occurredAt: e.target.value })} /><TextInput label="標題" value={record.title} onChange={(e) => setRecord({ ...record, title: e.target.value })} /><div className="ops-full"><Textarea label="完整內容" rows={5} value={record.content} onChange={(e) => setRecord({ ...record, content: e.target.value })} /></div></div><WarmButton onClick={() => void addRecord()}>新增紀錄</WarmButton><div className="ops-list">{selected.records.map((r) => <div className="ops-note" key={r.id}><div className="ops-note-actions"><strong>{r.title}</strong><button type="button" onClick={() => { if (confirm('封存這筆紀錄？')) void archiveServiceRecord(r.id).then(reload); }}>封存</button></div><p>{r.content}</p><small>{r.kind} · {new Date(r.occurredAt).toLocaleString('zh-TW')} · 第 {r.revision ?? 1} 版</small></div>)}</div></article></> : null}</main>
  </div>}</section>;
}

