import { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { adminListSessions } from '@/lib/api';
import type { SessionSlot } from '@contracts/types';
import { TextInput, Textarea, Select } from '@/components/ui/FormField/FormField';
import { WarmButton } from '@/components/ui/WarmButton/WarmButton';
import { createCaseFromRegistration, listContacts, listNotes, moveRegistrationSessions, saveNote, saveTask, transitionRegistration, updateRegistrationAdministration } from '../operations/api';
import type { ContactRecord, InternalNote, OperationalRegistration, WorkPriority } from '../operations/types';
import { EmptyPanel, InlineSpinner, OpsNotice, PageHeader, StatusPill } from '../operations/components';

const STATUS_OPTIONS = ['pending', 'reviewing', 'confirmed', 'success', 'waitlist', 'rejected', 'withdrawn', 'cancelled'];
const STATUS_LABEL: Record<string, string> = { pending: '待審核', reviewing: '審核中', confirmed: '已確認', success: '錄取／完成', waitlist: '候補', rejected: '不符合', withdrawn: '中途放棄', cancelled: '已取消' };
// 由報名頁注入、不在 form_schemas 裡的 answers key，給它們可讀標題。
const ANSWER_LABEL: Record<string, string> = { preferredExactSlots: '可配合的確切時段（報名者勾選）', sessionIds: '選擇場次' };

export default function RegistrationsOperationsPage() {
  const [searchParams] = useSearchParams();
  const [contacts, setContacts] = useState<ContactRecord[]>([]); const [sessions, setSessions] = useState<SessionSlot[]>([]); const [selectedId, setSelectedId] = useState<string>(); const [notes, setNotes] = useState<InternalNote[]>([]); const [search, setSearch] = useState(''); const [statusFilter, setStatusFilter] = useState('active'); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState<string>(); const [error, setError] = useState<string>();
  const registrations = useMemo(() => contacts.flatMap((contact) => contact.registrations.map((registration) => ({ registration, contact }))), [contacts]);
  const current = registrations.find(({ registration }) => registration.id === selectedId);
  const [draft, setDraft] = useState<Partial<OperationalRegistration>>({}); const [answers, setAnswers] = useState<Record<string, string | string[] | Record<string, string | string[]>[]>>({}); const [note, setNote] = useState(''); const [noteType, setNoteType] = useState<'general' | 'eligibility' | 'handoff' | 'risk'>('general'); const [caseSummary, setCaseSummary] = useState('');
  const reload = async () => { const [people, slots] = await Promise.all([listContacts(), adminListSessions()]); setContacts(people); setSessions(slots); const all = people.flatMap((p) => p.registrations); if (!selectedId && all[0]) setSelectedId(all[0].id); };
  useEffect(() => { reload().catch((e: unknown) => setError(e instanceof Error ? e.message : '讀取報名失敗')).finally(() => setLoading(false)); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => {
    const requested = searchParams.get('registration');
    if (requested && registrations.some(({ registration }) => registration.id === requested)) setSelectedId(requested);
  }, [registrations, searchParams]);  useEffect(() => { if (!current) return; setDraft({ ...current.registration }); setAnswers({ ...current.registration.answers }); listNotes({ registrationId: current.registration.id }).then(setNotes).catch(() => setNotes([])); }, [selectedId, contacts]); // eslint-disable-line react-hooks/exhaustive-deps
  const filtered = useMemo(() => registrations.filter(({ registration, contact }) => { const text = `${contact.displayName} ${contact.primaryEmail} ${registration.email} ${registration.projectName}`.toLowerCase(); const active = !['rejected', 'withdrawn', 'cancelled'].includes(registration.status); return text.includes(search.toLowerCase()) && (statusFilter === 'all' || (statusFilter === 'active' ? active : registration.status === statusFilter)); }), [registrations, search, statusFilter]);
  const saveAdmin = async () => { if (!current) return; try { await updateRegistrationAdministration(current.registration.id, { answers, priority: draft.priority as WorkPriority, assignedTo: draft.assignedTo || null, nextActionAt: draft.nextActionAt || null }); await reload(); setNotice('報名資料與行政欄位已更新。'); } catch (e) { setError(e instanceof Error ? e.message : '更新失敗'); } };
  const changeStatus = async (status: string) => { if (!current) return; try { await transitionRegistration(current.registration.id, status); await reload(); setNotice(`狀態已變更為「${STATUS_LABEL[status] ?? status}」，名額同步更新。`); } catch (e) { setError(e instanceof Error ? e.message : '狀態更新失敗'); } };
  const toggleSession = (id: string) => { const ids = draft.sessionIds ?? []; setDraft({ ...draft, sessionIds: ids.includes(id) ? ids.filter((v) => v !== id) : [...ids, id] }); };
  const saveSessions = async () => { if (!current) return; try { await moveRegistrationSessions(current.registration.id, draft.sessionIds ?? []); await reload(); setNotice('報名場次已原子移轉，原場次與新場次名額已同步。'); } catch (e) { setError(e instanceof Error ? e.message : '場次移轉失敗'); } };
  const addNote = async () => { if (!current || !note.trim()) return; await saveNote({ contactId: current.contact.id, registrationId: current.registration.id, noteType, content: note }); setNote(''); setNotes(await listNotes({ registrationId: current.registration.id })); };
  const addTask = async () => { if (!current) return; await saveTask({ projectId: current.registration.projectId, contactId: current.contact.id, registrationId: current.registration.id, title: `跟進報名：${current.contact.displayName}`, priority: draft.priority ?? 'normal', dueAt: draft.nextActionAt, status: 'open' }); setNotice('已建立追蹤待辦。'); };
  const createCase = async () => { if (!current) return; try { await createCaseFromRegistration(current.registration.id, 'ongoing', caseSummary); setNotice('已由報名建立個案，並保留人物與活動關聯。'); setCaseSummary(''); } catch (e) { setError(e instanceof Error ? e.message : '轉案失敗'); } };
  const answerEntries = Object.entries(answers);
  return <section className="ops-section"><PageHeader eyebrow="受理與審核" title="報名工作台" description="同一頁完成資料補正、註記、狀態、分派、轉場、寄信與轉案。" />{notice ? <OpsNotice tone="success">{notice}</OpsNotice> : null}{error ? <OpsNotice tone="danger">{error}</OpsNotice> : null}
    <div className="ops-toolbar"><TextInput label="搜尋" placeholder="姓名、Email、計畫" value={search} onChange={(e) => setSearch(e.target.value)} /><Select label="狀態" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}><option value="active">處理中</option><option value="all">全部</option>{STATUS_OPTIONS.map((status) => <option value={status} key={status}>{STATUS_LABEL[status]}</option>)}</Select></div>
    {loading ? <InlineSpinner /> : <div className="ops-split"><aside className="ops-panel ops-panel--flush">{filtered.length ? <div className="ops-list">{filtered.map(({ registration, contact }) => <button type="button" key={registration.id} className={`ops-list-button ${registration.id === selectedId ? 'ops-list-button--active' : ''}`} onClick={() => setSelectedId(registration.id)}><div><strong>{contact.displayName || registration.email}</strong><p>{registration.projectName} · {new Date(registration.createdAt).toLocaleDateString('zh-TW')}</p></div><StatusPill tone={registration.hasUnreadReply ? 'coral' : registration.status === 'confirmed' ? 'green' : 'yellow'}>{registration.hasUnreadReply ? '有回信' : STATUS_LABEL[registration.status] ?? registration.status}</StatusPill></button>)}</div> : <EmptyPanel title="沒有符合條件的報名" />}</aside>
      <main className="ops-section">{current ? <><article className="ops-panel"><div className="ops-detail-header"><div><p className="ops-eyebrow">{current.registration.projectName}</p><h2>{current.contact.displayName}</h2><p>{current.registration.email}</p></div><div className="ops-button-row"><Link className="ops-link-button" to={`/admin/inbox?registration=${current.registration.id}`}>查看信件往來</Link><Link className="ops-link-button" to={`/admin/people?contact=${current.contact.id}`}>人物主檔</Link></div></div><div className="ops-form-grid"><Select label="報名狀態" value={draft.status ?? current.registration.status} onChange={(e) => { setDraft({ ...draft, status: e.target.value }); void changeStatus(e.target.value); }}>{STATUS_OPTIONS.map((status) => <option value={status} key={status}>{STATUS_LABEL[status]}</option>)}</Select><Select label="優先度" value={draft.priority ?? 'normal'} onChange={(e) => setDraft({ ...draft, priority: e.target.value as WorkPriority })}><option value="low">低</option><option value="normal">一般</option><option value="high">高</option><option value="urgent">緊急</option></Select><TextInput type="datetime-local" label="下一步時間" value={draft.nextActionAt?.slice(0, 16) ?? ''} onChange={(e) => setDraft({ ...draft, nextActionAt: e.target.value ? new Date(e.target.value).toISOString() : undefined })} /><TextInput label="負責人 UUID" value={draft.assignedTo ?? ''} onChange={(e) => setDraft({ ...draft, assignedTo: e.target.value })} placeholder="可留空" /></div><div className="ops-button-row"><WarmButton onClick={() => void saveAdmin()}>儲存行政欄位</WarmButton><WarmButton variant="secondary" onClick={() => void addTask()}>建立追蹤</WarmButton></div></article>
      <article className="ops-panel"><div className="ops-panel-header"><div><h2>完整表單內容</h2><p>可補正缺漏資訊；所有欄位完整保留。</p></div></div>{answerEntries.length ? <div className="ops-form-grid">{answerEntries.map(([key, value]) => <Textarea key={key} label={ANSWER_LABEL[key] ?? key} value={Array.isArray(value) ? value.join('\n') : value} onChange={(e) => setAnswers({ ...answers, [key]: Array.isArray(value) ? e.target.value.split('\n').filter(Boolean) : e.target.value })} />)}</div> : <EmptyPanel title="這筆報名沒有表單內容" />}</article>
      <article className="ops-panel"><div className="ops-panel-header"><h2>場次移轉</h2></div><div className="ops-list">{sessions.filter((s) => s.projectId === current.registration.projectId).map((session) => <label className="ops-list-row" key={session.id}><span><input type="checkbox" checked={(draft.sessionIds ?? []).includes(session.id)} onChange={() => toggleSession(session.id)} /> <strong>{session.title}</strong></span><small>{new Date(session.startsAt).toLocaleString('zh-TW')} · {session.bookedCount}/{session.capacity}</small></label>)}</div><WarmButton onClick={() => void saveSessions()}>確認移轉場次</WarmButton></article>
      <article className="ops-panel"><div className="ops-panel-header"><h2>內部註記</h2></div><div className="ops-form-grid"><Select label="類型" value={noteType} onChange={(e) => setNoteType(e.target.value as typeof noteType)}><option value="general">一般</option><option value="eligibility">資格審核</option><option value="handoff">交接</option><option value="risk">風險</option></Select><div className="ops-full"><Textarea label="註記內容" rows={4} value={note} onChange={(e) => setNote(e.target.value)} /></div></div><WarmButton onClick={() => void addNote()}>新增註記</WarmButton>{notes.map((item) => <div className="ops-note" key={item.id}><p>{item.content}</p><small>{item.noteType} · 第 {item.revision} 版 · {new Date(item.createdAt).toLocaleString('zh-TW')}</small></div>)}</article>
      <article className="ops-panel"><div className="ops-panel-header"><div><h2>轉為持續服務個案</h2><p>保留原報名、人物、活動和信件關聯。</p></div></div><Textarea label="轉案摘要" value={caseSummary} onChange={(e) => setCaseSummary(e.target.value)} /><WarmButton onClick={() => void createCase()}>建立個案</WarmButton></article></> : <EmptyPanel title="請選擇一筆報名" />}</main>
    </div>}
  </section>;
}

