import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertCircle, CheckCircle2, Clock3 } from 'lucide-react';
import { TextInput, Select } from '@/components/ui/FormField/FormField';
import { WarmButton } from '@/components/ui/WarmButton/WarmButton';
import { listContacts, listTasks, saveTask } from '../operations/api';
import type { ContactRecord, FollowUpTask, TaskStatus } from '../operations/types';
import { EmptyPanel, InlineSpinner, MetricCard, OpsNotice, PageHeader, StatusPill } from '../operations/components';

const STATUS_LABELS: Record<TaskStatus, string> = { open: '待辦', in_progress: '進行中', snoozed: '已延後', done: '完成', cancelled: '取消' };

export default function TasksPage() {
  const [tasks, setTasks] = useState<FollowUpTask[]>([]); const [contacts, setContacts] = useState<ContactRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>(); const [notice, setNotice] = useState<string>(); const [filter, setFilter] = useState('active'); const [query, setQuery] = useState('');
  const reload = useCallback(async () => { try { const [nextTasks, nextContacts] = await Promise.all([listTasks(), listContacts()]); setTasks(nextTasks); setContacts(nextContacts); setError(undefined); } catch (err) { setError(err instanceof Error ? err.message : '讀取任務失敗'); } finally { setLoading(false); } }, []);
  useEffect(() => { void reload(); }, [reload]);
  const contactNames = useMemo(() => new Map(contacts.map((item) => [item.id, item.displayName])), [contacts]);
  const now = Date.now(); const overdue = tasks.filter((task) => task.status !== 'done' && task.dueAt && new Date(task.dueAt).getTime() < now).length; const dueToday = tasks.filter((task) => task.status !== 'done' && task.dueAt && new Date(task.dueAt).toDateString() === new Date().toDateString()).length;
  const filtered = tasks.filter((task) => { const active = !['done', 'cancelled'].includes(task.status); const byFilter = filter === 'all' || (filter === 'active' && active) || task.status === filter || (filter === 'overdue' && active && task.dueAt && new Date(task.dueAt).getTime() < now); const text = `${task.title} ${task.description ?? ''} ${task.contactId ? contactNames.get(task.contactId) ?? '' : ''}`.toLowerCase(); return byFilter && (!query.trim() || text.includes(query.trim().toLowerCase())); });
  async function setStatus(task: FollowUpTask, status: TaskStatus) { try { await saveTask({ ...task, id: task.id, status }); setNotice(status === 'done' ? `「${task.title}」已完成。` : '任務狀態已更新。'); await reload(); } catch (err) { setError(err instanceof Error ? err.message : '更新任務失敗'); } }
  return <div><PageHeader eyebrow="Work Queue" title="追蹤任務" description="把待回覆、補件、回電、確認場次與個案追蹤變成有負責人和期限的工作，不再依賴記憶。" />{notice ? <OpsNotice tone="success">{notice}</OpsNotice> : null}{error ? <OpsNotice tone="danger" role="alert">{error}</OpsNotice> : null}<div className="ops-metrics"><MetricCard label="待處理" value={tasks.filter((task) => !['done', 'cancelled'].includes(task.status)).length} tone="blue" /><MetricCard label="今日到期" value={dueToday} tone="yellow" /><MetricCard label="已逾期" value={overdue} tone="coral" /><MetricCard label="已完成" value={tasks.filter((task) => task.status === 'done').length} tone="green" /></div><div className="ops-toolbar"><div className="ops-search"><TextInput label="搜尋任務" name="task-search" value={query} onChange={(e) => setQuery(e.target.value)} /></div><Select label="任務檢視" name="task-filter" value={filter} onChange={(e) => setFilter(e.target.value)} options={[{ value: 'active', label: '尚未完成' }, { value: 'overdue', label: '已逾期' }, { value: 'open', label: '待辦' }, { value: 'in_progress', label: '進行中' }, { value: 'snoozed', label: '已延後' }, { value: 'done', label: '已完成' }, { value: 'all', label: '全部' }]} /></div>{loading ? <InlineSpinner label="整理工作佇列…" /> : <section className="ops-panel ops-panel--flush"><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>任務</th><th>關聯人員</th><th>優先度</th><th>期限</th><th>狀態</th><th>操作</th></tr></thead><tbody>{filtered.map((task) => { const isOverdue = task.status !== 'done' && task.dueAt && new Date(task.dueAt).getTime() < now; return <tr key={task.id}><td><strong>{task.title}</strong>{task.description ? <small style={{ display: 'block', color: '#806b62', marginTop: '.25rem' }}>{task.description}</small> : null}</td><td>{task.contactId ? contactNames.get(task.contactId) || '人員主檔' : '—'}</td><td><StatusPill tone={task.priority === 'urgent' ? 'red' : task.priority === 'high' ? 'coral' : 'gray'}>{priorityLabel(task.priority)}</StatusPill></td><td>{task.dueAt ? <span style={{ color: isOverdue ? '#a33e2a' : undefined }}>{isOverdue ? <AlertCircle size={15} style={{ display: 'inline', verticalAlign: '-2px' }} /> : <Clock3 size={15} style={{ display: 'inline', verticalAlign: '-2px' }} />} {formatDate(task.dueAt)}</span> : '未設定'}</td><td><StatusPill tone={task.status === 'done' ? 'green' : isOverdue ? 'red' : 'blue'}>{STATUS_LABELS[task.status]}</StatusPill></td><td><div className="ops-section-actions">{task.status !== 'done' ? <><WarmButton size="sm" variant="secondary" onClick={() => void setStatus(task, 'in_progress')}>進行中</WarmButton><WarmButton size="sm" icon={CheckCircle2} onClick={() => void setStatus(task, 'done')}>完成</WarmButton></> : <WarmButton size="sm" variant="secondary" onClick={() => void setStatus(task, 'open')}>重新開啟</WarmButton>}</div></td></tr>; })}</tbody></table></div>{!filtered.length ? <EmptyPanel title="這個檢視目前沒有任務" /> : null}</section>}</div>;
}
function formatDate(value: string) { return new Date(value).toLocaleString('zh-TW', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }); }
function priorityLabel(value: FollowUpTask['priority']) { return ({ low: '低', normal: '一般', high: '高', urgent: '緊急' } as const)[value]; }

