import type { InputHTMLAttributes, ReactNode, SelectHTMLAttributes, TextareaHTMLAttributes } from 'react';
export interface FieldFrameProps { /** Visible field label. */ label: string; /** Input id. */ id: string; /** Marks the label as required. */ required?: boolean; /** Optional helper copy. */ helpText?: string; /** Validation error. */ error?: string; /** Field input. */ children: ReactNode; }
/** Shared label, help-text and validation layout for form controls. */
export function FieldFrame({label,id,required,helpText,error,children}:FieldFrameProps){return <div className={`ui-field ${error?'ui-field--error':''}`}><label className="ui-field__label" htmlFor={id}>{label}{required?<span className="ui-field__required">*</span>:null}</label>{children}{error?<span className="ui-field__error" id={`${id}-error`}>{error}</span>:helpText?<span className="ui-field__help" id={`${id}-help`}>{helpText}</span>:null}</div>}
export interface TextInputProps extends InputHTMLAttributes<HTMLInputElement> { label:string; helpText?:string; error?:string; }
/** Branded text/email/phone input. */ export function TextInput({label,helpText,error,id,required,...props}:TextInputProps){const inputId=id??props.name??label;return <FieldFrame label={label} id={inputId} required={required} helpText={helpText} error={error}><input className="ui-field__control" id={inputId} required={required} aria-describedby={error?`${inputId}-error`:helpText?`${inputId}-help`:undefined} {...props}/></FieldFrame>}
export interface TextareaProps extends TextareaHTMLAttributes<HTMLTextAreaElement> { label:string; helpText?:string; error?:string; }
/** Branded multi-line input. */ export function Textarea({label,helpText,error,id,required,...props}:TextareaProps){const inputId=id??props.name??label;return <FieldFrame label={label} id={inputId} required={required} helpText={helpText} error={error}><textarea className="ui-field__control" id={inputId} required={required} aria-describedby={error?`${inputId}-error`:helpText?`${inputId}-help`:undefined} {...props}/></FieldFrame>}
export interface SelectProps extends SelectHTMLAttributes<HTMLSelectElement> { label:string; helpText?:string; error?:string; options:{label:string;value:string;disabled?:boolean}[]; }
/** Branded select field. */ export function Select({label,helpText,error,options,id,required,...props}:SelectProps){const inputId=id??props.name??label;return <FieldFrame label={label} id={inputId} required={required} helpText={helpText} error={error}><select className="ui-field__control" id={inputId} required={required} aria-describedby={error?`${inputId}-error`:helpText?`${inputId}-help`:undefined} {...props}>{options.map(option=><option key={option.value} value={option.value} disabled={option.disabled}>{option.label}</option>)}</select></FieldFrame>}
export interface Choice { label:string; value:string; disabled?:boolean; }
export interface ChoiceGroupProps { label:string; name:string; options:Choice[]; value?:string[]; onChange?:(values:string[])=>void; helpText?:string; error?:string; required?:boolean; }
/** Checkbox group that returns the selected values. */ export function CheckboxGroup({label,name,options,value=[],onChange,helpText,error,required}:ChoiceGroupProps){const id=name;const update=(valueName:string,checked:boolean)=>onChange?.(checked?[...value,valueName]:value.filter(item=>item!==valueName));return <FieldFrame label={label} id={id} required={required} helpText={helpText} error={error}><div className="ui-choice-group" role="group" aria-describedby={error?`${id}-error`:helpText?`${id}-help`:undefined}>{options.map(option=><label className="ui-choice" key={option.value}><input type="checkbox" name={name} value={option.value} checked={value.includes(option.value)} disabled={option.disabled} onChange={event=>update(option.value,event.target.checked)}/>{option.label}</label>)}</div></FieldFrame>}
export interface RadioGroupProps { label:string; name:string; options:Choice[]; value?:string; onChange?:(value:string)=>void; helpText?:string; error?:string; required?:boolean; }
/** Radio group for a single selection. */ export function RadioGroup({label,name,options,value,onChange,helpText,error,required}:RadioGroupProps){const id=name;return <FieldFrame label={label} id={id} required={required} helpText={helpText} error={error}><div className="ui-choice-group" role="radiogroup" aria-describedby={error?`${id}-error`:helpText?`${id}-help`:undefined}>{options.map(option=><label className="ui-choice" key={option.value}><input type="radio" name={name} value={option.value} checked={value===option.value} disabled={option.disabled} required={required} onChange={()=>onChange?.(option.value)}/>{option.label}</label>)}</div></FieldFrame>}
