import { CalendarPlus, Edit3, Plus } from 'lucide-react'; import { useState } from 'react';
import type { Instructor, SessionSlot, SessionStatus } from '@contracts/types';
import { DataTable } from '@/components/ui/DataTable'; import { Modal } from '@/components/ui/Modal'; import { Select, TextInput } from '@/components/ui/FormField'; import { WarmButton } from '@/components/ui/WarmButton';
import './session-manager.css';
export interface SessionManagerProps { sessions: SessionSlot[]; instructors: Instructor[]; onSave: (session: SessionSlot) => void; onCreateCalendarEvent: (session: SessionSlot) => void; }
const statuses: SessionStatus[]=['open','full','closed','cancelled']; const labels:Record<SessionStatus,string>={open:'開放報名',full:'額滿',closed:'關閉',done:'已完成',cancelled:'已取消'};
/** Session table and modal editor; all persistence is delegated to props. */ export function SessionManager({sessions,instructors,onSave,onCreateCalendarEvent}:SessionManagerProps){const [editing,setEditing]=useState<SessionSlot>(); const draft=editing; return <><div className="session-manager__head"><h2>場次管理</h2><WarmButton icon={Plus} onClick={()=>setEditing({id:`draft-${crypto.randomUUID()}`,projectId:'',title:'',startsAt:'',endsAt:'',capacity:1,bookedCount:0,status:'open',instructorIds:[]})}>新增場次</WarmButton></div><DataTable rows={sessions} getRowKey={row=>row.id} columns={[{id:'title',header:'場次',cell:row=>row.title,sortValue:row=>row.title},{id:'time',header:'時間',cell:row=>`${row.startsAt} ～ ${row.endsAt}`},{id:'capacity',header:'名額',cell:row=><Capacity value={row.bookedCount} max={row.capacity}/>,sortValue:row=>row.bookedCount},{id:'status',header:'狀態',cell:row=>labels[row.status]},{id:'actions',header:'操作',cell:row=><span className="session-manager__actions"><WarmButton size="sm" variant="secondary" icon={Edit3} onClick={()=>setEditing(row)}>編輯</WarmButton><WarmButton size="sm" icon={CalendarPlus} onClick={()=>onCreateCalendarEvent(row)}>Meet＋行事曆</WarmButton></span>}]}/><Modal open={Boolean(draft)} onClose={()=>setEditing(undefined)} title={draft?.title?'編輯場次':'新增場次'} footer={<><WarmButton variant="secondary" onClick={()=>setEditing(undefined)}>取消</WarmButton><WarmButton onClick={()=>{if(draft){onSave(draft);setEditing(undefined)}}}>儲存</WarmButton></>}>{draft?<SessionForm session={draft} instructors={instructors} onChange={setEditing}/>:null}</Modal></>}
function Capacity({value,max}:{value:number;max:number}){const percent=Math.min(100,Math.round(value/Math.max(1,max)*100));return <span className="session-manager__capacity"><span><i style={{width:`${percent}%`}}/></span>{value}/{max}</span>}
function SessionForm({session,instructors,onChange}:{session:SessionSlot;instructors:Instructor[];onChange:(session:SessionSlot)=>void}){const patch=(value:Partial<SessionSlot>)=>onChange({...session,...value});return <div className="session-manager__form"><TextInput label="場次標題" name="title" value={session.title} onChange={event=>patch({title:event.target.value})}/><TextInput label="開始時間" name="startsAt" type="datetime-local" value={session.startsAt} onChange={event=>patch({startsAt:event.target.value})}/><TextInput label="結束時間" name="endsAt" type="datetime-local" value={session.endsAt} onChange={event=>patch({endsAt:event.target.value})}/><TextInput label="名額" name="capacity" type="number" min="1" value={session.capacity} onChange={event=>patch({capacity:Number(event.target.value)})}/><Select label="狀態" name="status" value={session.status} onChange={event=>patch({status:event.target.value as SessionStatus})} options={statuses.map(status=>({value:status,label:labels[status]}))}/><fieldset><legend>講師</legend>{instructors.map(instructor=><label key={instructor.id}><input type="checkbox" checked={session.instructorIds.includes(instructor.id)} onChange={event=>patch({instructorIds:event.target.checked?[...session.instructorIds,instructor.id]:session.instructorIds.filter(id=>id!==instructor.id)})}/>{instructor.name}</label>)}</fieldset></div>}
